version: "3"

services:
  database:
    build:
      context: "./docker/build"
      dockerfile: "./server/mysql/Dockerfile"
    container_name: 'craft-database'
    restart: 'always'
    platform: "linux/x86_64"
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./docker/runtime/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./docker/runtime/logs/mysql}:/var/log/mysql
      - ./docker/build/craftcms-seeds/mysql/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  galapagos:
    tty: true
    build:
      context: "./docker/build"
      dockerfile: "./server/galapagos/Dockerfile"
    container_name: 'galapagos'
    ports:
      - "${HOST_MACHINE_GALAPAGOS_PORT}:${HOST_MACHINE_GALAPAGOS_PORT}"
    volumes: 
      - ./docker/build/galapagos-source:/app
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4096M
        reservations:
          cpus: "2"
          memory: 4096M
  webserver:
    build: 
      context: "./docker/build"
      dockerfile: "./server/ubuntu/Dockerfile"
    container_name: 'craft-webserver'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    depends_on:
      - database
    links: 
      - database
    volumes: 
      - ${PLUGIN_SRC-.src/craft-plugin}:${PLUGIN_DEST}
      - ${VHOSTS_DIR-./docker/build/craftcms-seeds/apache}:/etc/apache2/sites-enabled
      - ${PHP_INI-./docker/build/craftcms-seeds/php/craftcms.ini}:/etc/php/7.4/apache2/conf.d/30-craftcms.ini
      - ${LOG_DIR-./docker/runtime/logs/apache2}:/var/log/apache2
      - "./src/craft/schemas:/var/www/craftcms/schemas"
      - "./src/craft/migrations:/var/www/craftcms/migrations"
      - "./src/craft/web:/var/www/craftcms/web"
      - "./src/craft/templates:/var/www/craftcms/templates"
      - "./src/craft/config/htmlpurifier:/var/www/craftcms/config/htmlpurifier"
      - "./src/craft/config/redactor:/var/www/craftcms/config/redactor"
      - "./src/craft/config/app.php:/var/www/craftcms/config/app.php"
      - "./src/craft/config/general.php:/var/www/craftcms/config/general.php"
      - "./src/craft/config/routes.php:/var/www/craftcms/config/routes.php"
      - "./docker/runtime/logs/mysql:/var/log/mysql/general-log.log"
      - "./docker/runtime/logs/craft:/var/www/craftcms/storage/logs"
      - "./docker/build/scripts/install.sh:/usr/local/bin/plugin-install.sh"
      - "./docker/build/scripts/wait-for-it.sh:/usr/local/bin/wait-for-it.sh"
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/craftcms/web}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PRIMARY_SITE_URL: ${PRIMARY_SITE_URL}
      MIGRATION_ASSET_URL: ${MIGRATION_ASSET_URL}
      ENVIRONMENT: ${ENVIRONMENT}
      APP_ID: ${APP_ID}
      SECURITY_KEY: ${SECURITY_KEY}
      DB_DRIVER: ${DB_DRIVER}
      DB_SERVER: ${DB_SERVER}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_TABLE_PREFIX: ${DB_TABLE_PREFIX}
      CP_TRIGGER: ${CP_TRIGGER}
      PLUGIN_HANDLE: ${PLUGIN_HANDLE}
      PLUGIN_SLUG: ${PLUGIN_SLUG}
      AWS_S3_KEY: ${AWS_S3_KEY}
      AWS_S3_SECRET: ${AWS_S3_SECRET}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}
    command: ["wait-for-it.sh", "database:3306", "--strict" , "--timeout=300", "--", "plugin-install.sh", "${PLUGIN_HANDLE}", "${PLUGIN_SLUG}"]